import { Component, OnInit } from '@angular/core';

interface MtgSet {
  value: string;
  viewValue: string;
}

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  // @ts-ignore
  selectedValue: string;


  sets: MtgSet[] = [
    {value: 'LEA', viewValue: 'Limited Edition Alpha'},
    {value: 'LEB', viewValue: 'Limited Edition Beta'},
    {value: '2ED', viewValue: 'Unlimited Edition'},
    {value: '3ED', viewValue: 'Revised Edition[II]'},
    {value: '4ED', viewValue: 'Fourth Edition'},
    {value: '5ED', viewValue: 'Fifth Edition'},
    {value: '6ED', viewValue: 'Classic Sixth Edition'},
    {value: '7ED', viewValue: 'Seventh Edition'},
    {value: '8ED', viewValue: 'Eighth Edition'},
    {value: '9ED', viewValue: 'Ninth Edition'},
    {value: '10E', viewValue: 'Tenth Edition'},
    {value: 'M10', viewValue: 'Magic 2010'},
    {value: 'M11', viewValue: 'Magic 2011'},
    {value: 'M12', viewValue: 'Magic 2012'},
    {value: 'M13', viewValue: 'Magic 2013'},
    {value: 'M14', viewValue: 'Magic 2014'},
    {value: 'M15', viewValue: 'Magic 2015'},
    {value: 'ORI', viewValue: 'Magic Origins'},
    {value: 'M19', viewValue: 'Core Set 2019'},
    {value: 'M20', viewValue: 'Core Set 2020'},
    {value: 'M21', viewValue: 'Core Set 2021'},
    {value: 'ARN', viewValue: 'Arabian Nights'},
    {value: 'ATQ', viewValue: 'Antiquities'},
    {value: 'LEG', viewValue: 'Legends'},
    {value: 'DRK', viewValue: 'The Dark'},
    {value: 'FEM', viewValue: 'Fallen Empires'},
    {value: 'ICE', viewValue: 'Ice Age'},
    {value: 'HML', viewValue: 'Homelands[IX]'},
    {value: 'ALL', viewValue: 'Alliances'},
    {value: 'MIR', viewValue: 'Mirage'},
    {value: 'VIS', viewValue: 'Visions'},
    {value: 'WTH', viewValue: 'Weatherlight'},
    {value: 'TMP', viewValue: 'Tempest'},
    {value: 'STH', viewValue: 'Stronghold'},
    {value: 'EXO', viewValue: 'Exodus'},
    {value: 'USG', viewValue: 'Urza\'s Saga'},
    {value: 'ULG', viewValue: 'Urza\'s Legacy'},
    {value: 'UDS', viewValue: 'Urza\'s Destiny'},
    {value: 'MMQ', viewValue: 'Mercadian Masques'},
    {value: 'NEM', viewValue: 'Nemesis'},
    {value: 'PCY', viewValue: 'Prophecy'},
    {value: 'INV', viewValue: 'Invasion'},
    {value: 'PLS', viewValue: 'Planeshift'},
    {value: 'APC', viewValue: 'Apocalypse'},
    {value: 'ODY', viewValue: 'Odyssey'},
    {value: 'TOR', viewValue: 'Torment'},
    {value: 'JUD', viewValue: 'Judgment'},
    {value: 'ONS', viewValue: 'Onslaught'},
    {value: 'LGN', viewValue: 'Legions'},
    {value: 'SCG', viewValue: 'Scourge'},
    {value: 'MRD', viewValue: 'Mirrodin'},
    {value: 'DST', viewValue: 'Darksteel'},
    {value: '5DN', viewValue: 'Fifth Dawn'},
    {value: 'CHK', viewValue: 'Champions of Kamigawa'},
    {value: 'BOK', viewValue: 'Betrayers of Kamigawa'},
    {value: 'SOK', viewValue: 'Saviors of Kamigawa'},
    {value: 'RAV', viewValue: 'Ravnica: City of Guilds'},
    {value: 'GPT', viewValue: 'Guildpact'},
    {value: 'DIS', viewValue: 'Dissension'},
    {value: 'CSP', viewValue: 'Coldsnap[IX]'},
    {value: 'TSP', viewValue: 'Time Spiral'},
    {value: 'PLC', viewValue: 'Planar Chaos'},
    {value: 'FUT', viewValue: 'Future Sight'},
    {value: 'LRW', viewValue: 'Lorwyn'},
    {value: 'MOR', viewValue: 'Morningtide'},
    {value: 'SHM', viewValue: 'Shadowmoor'},
    {value: 'EVE', viewValue: 'Eventide'},
    {value: 'ALA', viewValue: 'Shards of Alara'},
    {value: 'CON', viewValue: 'Conflux'},
    {value: 'ARB', viewValue: 'Alara Reborn'},
    {value: 'ZEN', viewValue: 'Zendikar'},
    {value: 'WWK', viewValue: 'Worldwake'},
    {value: 'ROE', viewValue: 'Rise of the Eldrazi'},
    {value: 'SOM', viewValue: 'Scars of Mirrodin'},
    {value: 'MBS', viewValue: 'Mirrodin Besieged'},
    {value: 'NPH', viewValue: 'New Phyrexia'},
    {value: 'ISD', viewValue: 'Innistrad'},
    {value: 'DKA', viewValue: 'Dark Ascension'},
    {value: 'AVR', viewValue: 'Avacyn Restored'},
    {value: 'RTR', viewValue: 'Return to Ravnica'},
    {value: 'GTC', viewValue: 'Gatecrash'},
    {value: 'DGM', viewValue: 'Dragon\'s Maze'},
    {value: 'THS', viewValue: 'Theros'},
    {value: 'BNG', viewValue: 'Born of the Gods'},
    {value: 'JOU', viewValue: 'Journey into Nyx'},
    {value: 'KTK', viewValue: 'Khans of Tarkir'},
    {value: 'FRF', viewValue: 'Fate Reforged'},
    {value: 'DTK', viewValue: 'Dragons of Tarkir'},
    {value: 'BFZ', viewValue: 'Battle for Zendikar'},
    {value: 'OGW', viewValue: 'Oath of the Gatewatch'},
    {value: 'SOI', viewValue: 'Shadows over Innistrad'},
    {value: 'EMN', viewValue: 'Eldritch Moon'},
    {value: 'KLD', viewValue: 'Kaladesh'},
    {value: 'AER', viewValue: 'Aether Revolt'},
    {value: 'AKH', viewValue: 'Amonkhet'},
    {value: 'HOU', viewValue: 'Hour of Devastation'},
    {value: 'XLN', viewValue: 'Ixalan'},
    {value: 'RIX', viewValue: 'Rivals of Ixalan'},
    {value: 'DOM', viewValue: 'Dominaria'},
    {value: 'GRN', viewValue: 'Guilds of Ravnica'},
    {value: 'RNA', viewValue: 'Ravnica Allegiance'},
    {value: 'WAR', viewValue: 'War of the Spark[132]'},
    {value: 'ELD', viewValue: 'Throne of Eldraine'},
    {value: 'THB', viewValue: 'Theros Beyond Death'},
    {value: 'IKO', viewValue: 'Ikoria: Lair of Behemoths'},
    {value: 'ZNR', viewValue: 'Zendikar Rising'},
    {value: 'KHM', viewValue: 'Kaldheim'},
    {value: 'STX', viewValue: 'Strixhaven: School of Mages'},
    {value: 'AFR', viewValue: 'Dungeons & Dragons: Adventures in the Forgotten Realms'},
    {value: 'MID', viewValue: 'Innistrad: Midnight Hunt'},
    {value: 'VOW', viewValue: 'Innistrad: Crimson Vow'},
    {value: 'NEO', viewValue: 'Kamigawa: Neon Dynasty'},
    {value: 'SNC', viewValue: 'Streets of New Capenna'},
    {value: 'DMU', viewValue: 'Dominaria United'},
  ];
  constructor() { }

  ngOnInit(): void {
  }

}
